version: "3.9"

services:
  streamlit:
    build: .
    container_name: analytics_web
    ports:
      - "8501:8501"
    depends_on:
      - postgres
      - mysql
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: analytics
      PG_PASS: analytics123
      PG_DB: analytics

      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: analytics
      MYSQL_PASS: analytics123
      MYSQL_DB: analytics

    volumes:
      - ./db:/app/db
      - ./.env:/app/.env
    networks:
      - analytics-net

  postgres:
    image: postgres:15
    container_name: analytics_pg
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics123
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./sql/init_pg.sql:/docker-entrypoint-initdb.d/init_pg.sql
    networks:
      - analytics-net

  mysql:
    image: mysql:8
    container_name: analytics_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: analytics
      MYSQL_USER: analytics
      MYSQL_PASSWORD: analytics123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sql/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql
    networks:
      - analytics-net

  adminer:
    image: adminer
    container_name: analytics_adminer
    ports:
      - 8080:8080
    networks:
      - analytics-net

networks:
  analytics-net:
    driver: bridge
