version: "3.9"

services:

  backend:
    build:
      context: ./backend
    container_name: analytics_backend
    environment:
      DUCKDB_PATH: /data/event_log.duckdb
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: analytics
      PG_PASS: analytics123
      PG_DB: analytics
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: analytics
      MYSQL_PASS: analytics123
      MYSQL_DB: analytics
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - ./db:/data
    ports:
      - "8100:8000"
    depends_on:
      - postgres
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL=http://backend:8000
    container_name: analytics_frontend
    ports:
      - "3100:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: analytics_pg
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics123
      POSTGRES_DB: analytics
    ports:
      - "55432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    container_name: analytics_mysql
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: analytics
      MYSQL_USER: analytics
      MYSQL_PASSWORD: analytics123
    ports:
      - "33306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
